name: Deploy Protection

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check protected files
        if: github.ref != 'refs/heads/main' # Only run this job for branches other than 'main'
        run: |
          FILES=$(git diff --name-only origin/main)
          for FILE in $FILES; do
            if [[ "$FILE" =~ ^(abc/|package.txt) ]]; then
              echo "Error: Only changes to protected files are allowed on the 'main' branch."
              exit 1
            fi
          done
